services:
  frontend:
    image: qubicle-ui
    container_name: qubicle-frontend 

    ports:
      - "5173:80"

  backend:
    image: qubicle-api
    container_name: qubicle-backend

    ports:
      - "8000:8000"
    environment:
      ALLOWED_HOSTS: ${ALLOWED_HOSTS}
      DB_NAME: ${DB_NAME}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      SECRET_KEY: ${SECRET_KEY}
      DEBUG: false 
      ELASTICSEARCH_HOST: http://elasticsearch:9200
      FRONTEND_ORIGIN: ${FRONTEND_ORIGIN}
    depends_on:
      - elasticsearch

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:9.5.0
    container_name: qubicle-elasticsearch

    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data

volumes:
  elasticsearch_data: