# Generated by Django 6.0.4 on 2026-05-12 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='number',
            field=models.CharField(blank=True, editable=False, max_length=30, null=True),
        ),
    ]
