# Generated by Django 6.0.4 on 2026-05-14 15:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0002_alter_issue_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueActivity',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('field', models.CharField(max_length=20)),
                ('old_value', models.CharField(max_length=20)),
                ('new_value', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField()),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_activity', to=settings.AUTH_USER_MODEL)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity', to='issues.issue')),
            ],
        ),
    ]
