# Generated by Django 6.0.5 on 2026-06-13 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0003_issueactivity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issueactivity',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
