# Generated by Django 6.1 on 2026-08-14 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0004_alter_issueactivity_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issueactivity',
            name='new_value',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='issueactivity',
            name='old_value',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
